### ISSUE TITLE
Error in the provided Fake results json file

### ISSUE THREAD

**Issue by tejan-rgb** [GT-Vision-Lab/VQA#13]
Hi @deshraj @dexter1691 @jiasenlu @StanislawAntol @jwyang @AishwaryaAgrawal,

The Fake Results JSON file provided has only 248349 entries for the train2014 images, while the total number of questions for train2014 images is 443757. Hence, an error is coming up while calculating the accuracy on the Fake Results JSON file. Please do check it.

Thanks.

**Comment by AishwaryaAgrawal** [comment]
That file corresponds to VQA v1 not v2.

Best,
Aishwarya

**Comment by tejan-rgb** [comment]
Ok, thanks.

Thanks
Tejan Mehndiratta
