### ISSUE TITLE
Where can I find the test set?

### ISSUE THREAD

**Issue by dinhanhx** [GT-Vision-Lab/VQA#15]
![image](https://user-images.githubusercontent.com/38489776/229715666-58c8f6fc-f839-4dd3-8b36-21598023784d.png)

When I access [the website](https://visualqa.org/download.html), I see no links for test **answer** files.

**Comment by StanislawAntol** [comment]
As mentioned in https://github.com/GT-Vision-Lab/VQA/issues/3, please see the instructions on [the Challenge page](http://visualqa.org/challenge.html), as the test set is not public.

**Comment by sunnie-star** [comment]
> As mentioned in #3, please see the instructions on [the Challenge page](http://visualqa.org/challenge.html), as the test set is not public.

Thank you! However, how can I get the test accuracy since I cannot find submission entry after signing up as the instruction.
