### ISSUE TITLE
How to get the test-dev2015 accuracy?

### ISSUE THREAD

**Issue by xhzhao** [GT-Vision-Lab/VQA#3]
I can  get the accuracy of val using datatype val2014, through this file : https://github.com/VT-vision-lab/VQA/blob/master/PythonEvaluationTools/vqaEvalDemo.py.
But i have no idea how to get the test-dev accuracy on the papers, because there is no annotation file for test-dev on this page(http://www.visualqa.org/download.html).
The annotation files i can get are list as follows:
mscoco_train2014_annotations.json
mscoco_val2014_annotations.json

No annotation file for test-dev2015.
Any clue?

**Comment by StanislawAntol** [comment]
See the instructions on [the Challenge page](http://visualqa.org/challenge.html).

**Comment by UPCLJ** [comment]
> I can get the accuracy of val using datatype val2014, through this file : https://github.com/VT-vision-lab/VQA/blob/master/PythonEvaluationTools/vqaEvalDemo.py.
> But i have no idea how to get the test-dev accuracy on the papers, because there is no annotation file for test-dev on this page(http://www.visualqa.org/download.html).
> The annotation files i can get are list as follows:
> mscoco_train2014_annotations.json
> mscoco_val2014_annotations.json
> 
> No annotation file for test-dev2015.
> Any clue?

did you solve these problems?
I want to get test_annotations and test-dev_annotations too.

**Comment by sunnie-star** [comment]
> > I can get the accuracy of val using datatype val2014, through this file : https://github.com/VT-vision-lab/VQA/blob/master/PythonEvaluationTools/vqaEvalDemo.py.
> > But i have no idea how to get the test-dev accuracy on the papers, because there is no annotation file for test-dev on this page(http://www.visualqa.org/download.html).
> > The annotation files i can get are list as follows:
> > mscoco_train2014_annotations.json
> > mscoco_val2014_annotations.json
> > No annotation file for test-dev2015.
> > Any clue?
> 
> did you solve these problems? I want to get test_annotations and test-dev_annotations too.

Hello！Execuse me. Please did you solve this problem? I want to get test_annotations and test-dev_annotations too.
