### ISSUE TITLE
Any other ways to get result accuracy on test205 since the server is closed ?

### ISSUE THREAD

**Issue by daisysnow** [GT-Vision-Lab/VQA#6]
Hi,@AishwaryaAgrawal
    I want to get accuracy for test2015, but [the Challenge page ](http://visualqa.org/challenge_2016.html) told me the challenge is ended. But it worked yesterday.
    Is there any other ways for me to get the accuracy?

![image](https://user-images.githubusercontent.com/35361323/38065861-f10865e2-3337-11e8-9ceb-36c4106745e9.png)

**Comment by StanislawAntol** [comment]
The "Challenge test2015" submissions were purely for the VQA challenge (as part of the CVPR workshop). The non-Challenge test2015 "Codalab phase" should still be open for submitting results to and getting back accuracies (e.g., to report in papers).

**Comment by daisysnow** [comment]
@StanislawAntol  Thanks for your timely reply！
But I did not find the "Codalab phase", could you give me a link ?  It is really matters for me!
Thanks very much!

**Comment by daisysnow** [comment]
@StanislawAntol  
Sorry, I found that I was using the Codelab phase, but it said that it was closed, and I can not submit my result.
Any ideas about that?

**Comment by AishwaryaAgrawal** [comment]
Hi @daisysnow,

The issue seems to be at Codalab's end. We are working with Codalab admins to resolve the issue. 

We will let you know once the issue is resolved.

Best,
Aishwarya

**Comment by StanislawAntol** [comment]
There are no direct links. But, as an example, for the open-ended real competition, you can go [here](https://competitions.codalab.org/competitions/6961#participate-submit_results) and then click on "Real test2015 (oe)" and not "Real Challenge test2015 (oe)".

**Comment by daisysnow** [comment]
@AishwaryaAgrawal  @StanislawAntol  Thanks !

Hoping it can be resolved as soon as possible~
